CONFIG_STDOUT_CONSOLE=y

CONFIG_LOG=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
# CONFIG_USB_DEVICE_VID=0x1234
# CONFIG_USB_DEVICE_PID=0x2001
CONFIG_USB_DEVICE_MANUFACTURER="Zephyr"
CONFIG_USB_DEVICE_PRODUCT="Secure USB Mass"
CONFIG_USB_DEVICE_SN="0011223344556677"
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_REQUEST_BUFFER_SIZE=128

CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_RAM=y

CONFIG_MAIN_STACK_SIZE=4096
